### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by philehot** [snowflakedb/qgis-snowflake-plugin#2]
OS: Windows
QGIS version: 3.14.10.-Prizren

I can't load any layer. I can establish connexion but I'm getting an error for every single table I'm trying to load
2 types of error:
1) SFConvertColumnToLayerTask run failed: list index out of range. Same error if I execute as a SQL query. I add a where clause and I select the geopgraphy type
2) Running snowflake convert column to layer task failed. SQL Compilation error: error line x at position XX, invlaid indetifier 'SHAPEFILE/CENTROID/SHAPE_AREA/STOPTIME/METERS" The invalid identifier is not related to the geopgragy column. I'm not able to identify why it fails on those specific fields.

**Comment by sfc-gh-obielov** [comment]
Hey @philehot, please try out[ the latest version](https://drive.google.com/file/d/1vVe0X6OSCSysmK2Csm_5FscWUFyYDVUI/view?usp=sharing) and let mw know if it's still reproducible.

**Comment by philehot** [comment]
I thought initially we had some tables in our WH already converted to GEOGRAPHY but turns out this was not the case. Once I updated a geo column to TO_GEOGRAPHY, the table showed up in QGIS. Closing this as it was not an issue.
